import { StyleSheet } from 'react-native';

export const s = StyleSheet.create({
  // ── Flex / Layout ──
  flex1: { flex: 1 },
  flexRow: { flexDirection: 'row' },
  flexRowCenter: { flexDirection: 'row', alignItems: 'center' },
  flexRowCenterBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  flexCol: { flexDirection: 'column' },
  flexWrap: { flexWrap: 'wrap' },

  // Alignment
  itemsCenter: { alignItems: 'center' },
  itemsEnd: { alignItems: 'flex-end' },
  itemsStart: { alignItems: 'flex-start' },
  itemsStretch: { alignItems: 'stretch' },
  justifyCenter: { justifyContent: 'center' },
  justifyEnd: { justifyContent: 'flex-end' },
  justifyBetween: { justifyContent: 'space-between' },
  justifyAround: { justifyContent: 'space-around' },
  justifyStart: { justifyContent: 'flex-start' },
  selfCenter: { alignSelf: 'center' },
  selfStart: { alignSelf: 'flex-start' },
  selfEnd: { alignSelf: 'flex-end' },
  selfStretch: { alignSelf: 'stretch' },

  // ── Position ──
  absolute: { position: 'absolute' },
  relative: { position: 'relative' },

  // ── Overflow ──
  overflowHidden: { overflow: 'hidden' },
  overflowVisible: { overflow: 'visible' },

  // ── Width / Height ──
  wFull: { width: '100%' },
  hFull: { height: '100%' },
  w10: { width: 40 },
  w11: { width: 44 },
  w12: { width: 48 },
  w14: { width: 56 },
  w16: { width: 64 },
  w5: { width: 20 },
  w3: { width: 12 },
  w9: { width: 36 },
  h16: { height: 64 },
  h10: { height: 40 },
  h11: { height: 44 },
  h12: { height: 48 },
  h14: { height: 56 },
  h5: { height: 20 },
  h3: { height: 12 },
  h9: { height: 36 },
  h2px: { height: 2 },
  aspectSquare: { aspectRatio: 1 },

  // ── Padding ──
  p3: { padding: 12 },
  p4: { padding: 16 },
  p5: { padding: 20 },
  p8: { padding: 32 },
  px4: { paddingHorizontal: 16 },
  px5: { paddingHorizontal: 20 },
  px8: { paddingHorizontal: 32 },
  px3: { paddingHorizontal: 12 },
  px2: { paddingHorizontal: 8 },
  px1: { paddingHorizontal: 4 },
  px15: { paddingHorizontal: 6 },
  py3: { paddingVertical: 12 },
  py4: { paddingVertical: 16 },
  py2: { paddingVertical: 8 },
  py1: { paddingVertical: 4 },
  py15: { paddingVertical: 6 },
  py05: { paddingVertical: 2 },
  py6: { paddingVertical: 24 },
  py12: { paddingVertical: 48 },
  py16: { paddingVertical: 64 },
  py20: { paddingVertical: 80 },
  pt2: { paddingTop: 8 },
  pt3: { paddingTop: 12 },
  pt4: { paddingTop: 16 },
  pt8: { paddingTop: 32 },
  pt12: { paddingTop: 48 },
  pt14: { paddingTop: 56 },
  pb1: { paddingBottom: 4 },
  pb2: { paddingBottom: 8 },
  pb3: { paddingBottom: 12 },
  pb4: { paddingBottom: 16 },
  pb5: { paddingBottom: 20 },
  pb6: { paddingBottom: 24 },
  pb8: { paddingBottom: 32 },

  // ── Margin ──
  mb1: { marginBottom: 4 },
  mb2: { marginBottom: 8 },
  mb3: { marginBottom: 12 },
  mb4: { marginBottom: 16 },
  mb5: { marginBottom: 20 },
  mb6: { marginBottom: 24 },
  mb8: { marginBottom: 32 },
  mt1: { marginTop: 4 },
  mt8: { marginTop: 32 },
  mt2: { marginTop: 8 },
  mt3: { marginTop: 12 },
  mt4: { marginTop: 16 },
  mt6: { marginTop: 24 },
  mt05: { marginTop: 2 },
  mt12: { marginTop: 48 },
  ml15: { marginLeft: 6 },
  ml2: { marginLeft: 8 },
  mr2: { marginRight: 8 },
  mr3: { marginRight: 12 },
  mx05: { marginHorizontal: 2 },
  mx0: { marginHorizontal: 0 },
  mx4: { marginHorizontal: 16 },

  // ── Border Radius ──
  roundedXs: { borderRadius: 4 },
  roundedSm: { borderRadius: 6 },
  roundedLg: { borderRadius: 8 },
  roundedXl: { borderRadius: 12 },
  rounded2xl: { borderRadius: 16 },
  rounded3xl: { borderRadius: 24 },
  roundedFull: { borderRadius: 9999 },

  // ── Gap ──
  gap1: { gap: 4 },
  gap2: { gap: 8 },
  gap3: { gap: 12 },
  gap4: { gap: 16 },
  gap5: { gap: 20 },
  gap6: { gap: 24 },
  gap8: { gap: 32 },
  gap12: { gap: 48 },
  gap16: { gap: 64 },

  // ── Typography (static) ──
  text9: { fontSize: 9 },
  text10: { fontSize: 10 },
  textXs: { fontSize: 12 },
  textSm: { fontSize: 14 },
  textBase: { fontSize: 16 },
  textLg: { fontSize: 18 },
  textXl: { fontSize: 20 },
  text2xl: { fontSize: 24 },
  text3xl: { fontSize: 30 },
  text4xl: { fontSize: 36 },

  fontNormal: { fontWeight: '400' },
  fontMedium: { fontWeight: '500' },
  fontSemibold: { fontWeight: '600' },
  fontBold: { fontWeight: '700' },
  fontMono: { fontFamily: 'monospace' },

  textCenter: { textAlign: 'center' },
  textLeft: { textAlign: 'left' },
  uppercase: { textTransform: 'uppercase' },
  capitalize: { textTransform: 'capitalize' },

  // ── Border ──
  border0: { borderWidth: 0 },

  // ── Common combinations ──
  rowCenter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowCenterBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  center: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  fillCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  absoluteFill: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 9999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionLabel: {
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 12,
  },
  cardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    padding: 16,
  },
  cardIconBox: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
